HashTable implementation
MikeK93/DataStructureSamples pull request #3
Opened 2017-05-16 20:25 UTC by MikeK93

2017-05-17 09:37 UTC, smallnonsense requested changes
я закінчив по hashtable

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            _hashTable = new HashTable<string, string>();
особливого сенсу немає для ініціалізування поля в окремому методі. зручніше коли воно в кожному методі

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            // act & assert
коментарі не несуть ніякого навантаження

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            object value = null;
що робить ця змінна?

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            actual.ShouldBeEqualTo(Value);
де гарантія що воно витягує правильне значення, а не перше ліпше?

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            var actual = _hashTable.TryGet("invalid key", out string value);
яка гарантія, що в value лежить те що треба?

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            value.ShouldBeEqualTo(Value);
де гарантія що воно поверне правильне значення, а не перше ліпше?

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +                _hashTable.Add(item.Key, item.Value);
це краще робити через синтаксис Collection Initializers

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            var actual = new List<Entry<string, string>>();
чому це не зробити через linq в одну лінію?

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            actual.TrueForAll(entry => _hashTable.Contains(entry.Key)).ShouldBeTrue();
це було б більш показово через CollectionAssert якийсь, чи аналог

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures/Source/HashTable/HashTable.cs
> +                    continue;
continue/break - погана практика для циклів, бо зазивчай значить, що алгоритм не продуманий. взагалі важко читати і розуміти алгоритм, коли критеріїв виходу з циклу декілька

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures/Source/HashTable/HashTable.cs
> +            for (int i = 0; i < _entries.Length; i++)
перепиши одним запитом на linq. він вийде простіше і в одну лінію.

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures/Source/HashTable/HashTable.cs
> +            if (!updatable)
булеві параметри свідчать, що метод робить більше ніж повинен. тут є дві реальні поведінки які зараз звязані
1) strict - add
2) flexible - add or update
пропоную розбити код на два цих методи, які один одного використовують залежно від поведінки

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures/Source/HashTable/HashTable.cs
> +        private ILinkedList<Entry<TKey, TValue>>[] _entries;
щось на кшталт _baskets краще б відповідало змісту

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures/Source/HashTable/HashTable.cs
> +            for (var i = 0; i < _entries.Length; i++)
знову ж, цей цикл можна було б замінити на один linq запит, що зібрав би всі entry для подальшогро запиту до нового списку

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures/Source/HashTable/HashTable.cs
> +        private void TryResize()
схоже тут розглядається лише розширення. а що стосовно скорочення при мінімальному порозі?

2017-05-17 09:37 UTC, smallnonsense commented on DataStructures/Source/LinkedList/LinkedList.cs
>              }
прохання розділяти pull requests для кожного з завдань з окремої гілки. тобто LinkedList, Stack+Queue, HashTable і тд роздільно по гілкам та pull requests.
виправлення по ним, в ідеалі прикріпити до того самого pull request, а якщо так не можна то також окремо.

2017-05-17 10:11 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            _hashTable = new HashTable<string, string>();
мне нравиться SetUp метод тем что 
1. можно выносить повторяющиеся блоки (инициализация). Таким образом меньше дублирования в коде;
2. гарантия того что на начале теста будут всегда новые обьекты;

являеться ли это критическим?

2017-05-17 10:12 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            // act & assert
разбиение кода разве что. просто привык так писать и это особенно хорошо работает когда больной сетап какойто в тесте.

2017-05-17 10:13 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            actual.ShouldBeEqualTo(Value);
в том что там всего один элемент находиться

2017-05-17 10:13 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            object value = null;
просто что бы удовлетворить компилятор, т.к. `_hashTable["invalid key"]` возвращяет значение.

2017-05-17 10:14 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            var actual = _hashTable.TryGet("invalid key", out string value);
нужно проверить еще и value.

2017-05-17 10:22 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            value.ShouldBeEqualTo(Value);
в таблице только один элемент

2017-05-17 10:31 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +                _hashTable.Add(item.Key, item.Value);
done

2017-05-17 10:31 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            var actual = new List<Entry<string, string>>();
done

2017-05-17 10:32 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            actual.TrueForAll(entry => _hashTable.Contains(entry.Key)).ShouldBeTrue();
done

2017-05-17 10:32 UTC, MikeK93 commented on DataStructures/Source/HashTable/HashTable.cs
> +        private ILinkedList<Entry<TKey, TValue>>[] _entries;
done

2017-05-17 10:58 UTC, MikeK93 commented on DataStructures/Source/HashTable/HashTable.cs
> +            if (!updatable)
done

2017-05-17 11:00 UTC, MikeK93 commented on DataStructures/Source/HashTable/HashTable.cs
> +        private void TryResize()
много кто пишет что уменьшение не всегда хорошо, т.к. раз один раз был ресайз, нет гарантии что не будет еще раз.

2017-05-17 11:07 UTC, MikeK93 commented on DataStructures/Source/HashTable/HashTable.cs
> +            for (var i = 0; i < _entries.Length; i++)
done

2017-05-17 11:18 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            _hashTable = new HashTable<string, string>();
все правильно. але в даному випадку від ініціалізації лишається лише створення одного екземпляра.
це не є кретичним, але це просто зайва робота. якщо подобається то нехай лишається.

2017-05-17 11:18 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            // act & assert
добре. це справа кожного, але знову ж таки лишня робота і більший розмір файла. полегшення читання воно не добавить

2017-05-17 11:18 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            actual.ShouldBeEqualTo(Value);
ну я до того і вів. краще показати випадок коли є декілька елементів і він вибирає саме той з списку. бо в цьому воно доводить лише що можна витягнути один єдиний елемент

2017-05-17 11:18 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            object value = null;
так воно не обов"язкове і нормально ігнорується компілятором, якщо я не помиляюсь

2017-05-17 11:18 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            var actual = _hashTable.TryGet("invalid key", out string value);
саме так

2017-05-17 11:18 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            value.ShouldBeEqualTo(Value);
потрібно допряцювати вхідні умови. читай вище

2017-05-17 12:20 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            object value = null;
![image](https://cloud.githubusercontent.com/assets/9809523/26153505/5017b988-3b14-11e7-9566-bb5b6225c8e5.png)

2017-05-18 11:02 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            object value = null;
дійсно. нічого краще чим ізолювати змінну в середині не придумав.
() => { var value = _hashTable[""]; }

2017-05-18 11:07 UTC, smallnonsense commented on DataStructures/Source/HashTable/HashTable.cs
> +        private void TryResize()
ну "оптимальність" базується на компромісі. в .net якраз компромісний варіант.
ну нехай так лишається. в принципі зменшення працює аналогічно розширенню.

2017-05-18 14:34 UTC, smallnonsense requested changes

2017-05-18 14:34 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            _hashTable.Add("Key2", "2Value");
Тоді краще параметри щоб вде були оформлені в однаковому вигляді.

2017-05-18 14:34 UTC, smallnonsense commented on DataStructures/Source/HashTable/HashTable.cs
> +            foreach (var entry in _buckets.Where(bucket => bucket != null).SelectMany(bucket => bucket))
а навіщо тобі yield тепер, якщо в тебе готова енумерація?

2017-05-18 14:34 UTC, smallnonsense commented on DataStructures/Source/HashTable/HashTable.cs
> +            foreach (var entry in _buckets.Where(bucket => bucket != null).SelectMany(entry => entry))
а навіщо foreach, якщо в тебе колекція мапиться в колекцію?

2017-05-18 14:52 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            _hashTable.Add("Key2", "2Value");
done

2017-05-18 14:52 UTC, MikeK93 commented on DataStructures/Source/HashTable/HashTable.cs
> +            foreach (var entry in _buckets.Where(bucket => bucket != null).SelectMany(bucket => bucket))
done

2017-05-18 14:55 UTC, MikeK93 commented on DataStructures/Source/HashTable/HashTable.cs
> +            foreach (var entry in _buckets.Where(bucket => bucket != null).SelectMany(entry => entry))
не совсем так. поскольку новый массив бакетов в два раза больше, то расчет индекса для бакета будет отличаться. Таким образом элементы что были раньше в одном бакете могут быть в новом в новом массиве бакетов.

2017-05-24 13:31 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            _hashTable = new HashTable<string, string>();
оставлю :)

2017-05-24 13:31 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            actual.ShouldBeEqualTo(Value);
done

2017-05-24 13:31 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            object value = null;
done

2017-05-24 13:31 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            value.ShouldBeEqualTo(Value);
done

2017-05-24 13:32 UTC, MikeK93 commented on DataStructures/Source/HashTable/HashTable.cs
> +            for (int i = 0; i < _entries.Length; i++)
done

2017-05-24 13:32 UTC, MikeK93 commented on DataStructures/Source/HashTable/HashTable.cs
> +                    continue;
done

2017-05-24 14:27 UTC, smallnonsense commented on DataStructures/Source/HashTable/HashTable.cs
> +            foreach (var entry in _buckets.Where(bucket => bucket != null).SelectMany(entry => entry))
я трішки про інше. але написати цю логіку одним linq запитом мабуть буде складнувато і не так очевидно. Нехай так лишається. Все гаразд.

2017-05-25 08:31 UTC, smallnonsense requested changes

2017-05-25 08:31 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
>              _hashTable.Add(Key, Value);
добавляння 2-х елементів немає сенсу

2017-05-25 08:31 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +        public void Setter_ShouldRemoveElementAndUpdateCount_WhenSetNullValueForExistingKey()
видалення тут не перевіряється, тому не варто і згадувати

2017-05-25 08:31 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            //value.ShouldNotBeEqualTo(Value);
коментування коду в тесті є зайвим. видалив, або лишив

2017-05-25 08:31 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +        public void TryGet_ShouldSetValueToNull_WhenKeyWasNotFound()
неправда. що буде якщо Value буде число?

2017-05-25 08:31 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +        public void TryGet_ShoudSetOutParameterWithCorrectValue_WhenKeyExists()
описувати можифікатори немає сенсу. це повернене значення на рівні з успішністю операції.

2017-05-25 08:31 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            CollectionAssert.AreEqual(_hashTable.OrderBy(entry => entry.Key), expected);
ти ж використувував інший спосіб порівнювання колекцій, якщо я не помиляюсь. нехай все буде в одному стилі. Вибери один з них.

2017-05-25 08:31 UTC, smallnonsense commented on DataStructures/Contracts/IHashTable.cs
> +        /// <returns>Exists or no.</returns>
status if \<param key> was found

2017-05-25 08:31 UTC, smallnonsense commented on DataStructures/Contracts/IHashTable.cs
> +        /// <param name="key"></param>
порожні? і ці не єдині

2017-05-25 08:31 UTC, smallnonsense commented on DataStructures/Contracts/IHashTable.cs
> +        /// <returns>Value by a key.</returns>
Value associated with a \<param key>

2017-05-25 08:31 UTC, smallnonsense commented on DataStructures/Contracts/IHashTable.cs
> +        /// Gets count of entries in a table.
Сount of entries in a table

2017-05-25 08:31 UTC, smallnonsense commented on DataStructures/Source/HashTable/Entry.cs
> +        public override bool Equals(object obj)
пошукай на msdn рекомендовану реалізацію.

2017-05-25 12:03 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +        public void Setter_ShouldRemoveElementAndUpdateCount_WhenSetNullValueForExistingKey()
проверяеться удаление елемента из таблицы когда сетиться null

2017-05-25 12:04 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            //value.ShouldNotBeEqualTo(Value);
сори, удалил

2017-05-25 12:08 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +        public void TryGet_ShouldSetValueToNull_WhenKeyWasNotFound()
я имел ввиду что для конкретной HashTable<string, string> будет null. Переименую на TryGet_ShouldSetDefaultValueToValue_WhenKeyWasNotFound ?

2017-05-25 12:10 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +        public void TryGet_ShoudSetOutParameterWithCorrectValue_WhenKeyExists()
может вернуть false но значвение out параметра правильное. случай где возвращаеться правильное значение покрываеться, а это тест на то что параметр корректно заполнился.

2017-05-25 12:50 UTC, MikeK93 commented on DataStructures/Contracts/IHashTable.cs
> +        /// <returns>Exists or no.</returns>
done

2017-05-25 12:52 UTC, MikeK93 commented on DataStructures/Contracts/IHashTable.cs
> +        /// <param name="key"></param>
done

2017-05-25 12:53 UTC, MikeK93 commented on DataStructures/Contracts/IHashTable.cs
> +        /// <returns>Value by a key.</returns>
done

2017-05-25 13:07 UTC, MikeK93 commented on DataStructures/Source/HashTable/Entry.cs
> +        public override bool Equals(object obj)
done

2017-05-25 13:09 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            CollectionAssert.AreEqual(_hashTable.OrderBy(entry => entry.Key), expected);
done

2017-05-25 13:09 UTC, MikeK93 commented on DataStructures/Contracts/IHashTable.cs
> +        /// Gets count of entries in a table.
тоже что и тут https://github.com/MikeK93/DataStructureSamples/pull/1

2017-05-25 14:34 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +        public void Setter_ShouldRemoveElementAndUpdateCount_WhenSetNullValueForExistingKey()
перевірка видалення йде наступним тестом

2017-05-25 14:34 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +        public void TryGet_ShouldSetValueToNull_WhenKeyWasNotFound()
так, так краще

2017-05-25 14:37 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +        public void TryGet_ShoudSetOutParameterWithCorrectValue_WhenKeyExists()
я про назву тесту, ShouldSetOutParameter -> ShouldReturn (operation status / value associated with a key)

2017-05-25 14:52 UTC, smallnonsense requested changes

2017-05-25 14:52 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            _hashTable.AsEnumerable().ShouldBeEqualTo(expected);
а сортування вже не потрібне?

2017-05-25 14:52 UTC, smallnonsense commented on DataStructures/Contracts/IHashTable.cs
> +        /// <param name="value">Value of entry.</param>
можна було просто видалити. опис додаткової інформації не несе тут. 
відповідати не треба.

2017-05-25 14:52 UTC, smallnonsense commented on DataStructures/Source/HashTable/Entry.cs
> +        public bool AreEqual(Entry<TKey, TValue> obj1, Entry<TKey, TValue> obj2)
іменування відрізняється від стандартного. це розрив шаблона.

2017-05-25 14:52 UTC, smallnonsense commented on DataStructures/Source/HashTable/Entry.cs
> +            return obj1 != null && obj1.Key.Equals(obj2.Key) && obj1.Value.Equals(obj2.Value);
1) чи може obj2 бути null?
2) (obj1 != null) точно працює?

2017-05-26 12:41 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            _hashTable.AsEnumerable().ShouldBeEqualTo(expected);
нет ShouldBeEqualTo делает все

2017-05-26 13:12 UTC, smallnonsense commented on DataStructures/Source/HashTable/Entry.cs
> +            return obj != null && Key.Equals(obj.Key) && Value.Equals(obj.Value);
оператори можуть перевизначатись, тому надійніше використовувати ReferenceEquals. 
оператори надійно працюють лише з примітивами і то тільки якщо вони порівнюються з іншими примітивами. все інше неявно і вразливе до неявних помилок.

2017-05-27 15:38 UTC, MikeK93 commented on DataStructures/Source/HashTable/Entry.cs
> +            return obj1 != null && obj1.Key.Equals(obj2.Key) && obj1.Value.Equals(obj2.Value);
obj2 может быть null, а вот obj1 нет так как это this.
и этот метод должен быть private. 
но его уже нету, я переписал немного

2017-05-27 15:38 UTC, MikeK93 commented on DataStructures/Source/HashTable/Entry.cs
> +            return obj != null && Key.Equals(obj.Key) && Value.Equals(obj.Value);
got it

2017-05-30 08:12 UTC, smallnonsense requested changes

2017-05-30 08:12 UTC, smallnonsense commented on DataStructures/Source/HashTable/Entry.cs
> +                ReferenceEquals(this, obj) &&
от оце зайве. все що йде за ним нематиме сенсу.

2017-05-30 08:12 UTC, smallnonsense commented on DataStructures/Source/HashTable/Entry.cs
> +            return obj != null &&
а от тут і треба було використати ReferenceEquals

2017-06-01 09:21 UTC, smallnonsense requested changes

2017-06-01 09:21 UTC, smallnonsense commented on DataStructures/Source/HashTable/Entry.cs
> +            return obj != null &&
щось в цьому рядку я просив поміняти :)
я прошу відповідати на мої коментарі не лише, щоб я розумів чи ти щось робиш, а й тому щоб ти нічого не пропустив.

2017-06-01 21:22 UTC, MikeK93 commented on DataStructures/Source/HashTable/Entry.cs
> +            return obj != null &&
да, я тут сравиниваю по значению пропертей только.
это нормально что тест будет падать из-за того что сравниваються по ссылке. если юзать ReferenceEquals то нужно будет в тесте сравнивать значения тогда. 
нормально будет?
```C#
public void IEnumerableImplementation_ShouldBeAbleToIterateOverTable()
        {
            // arrange
            var expected = new[]
            {
                new Entry<string, string>("key1", "value1"),
                new Entry<string, string>("key2", "value2"),
                new Entry<string, string>("key3", "value3"),
                new Entry<string, string>("key4", "value4")
            };

            // act
            _hashTable = new HashTable<string, string>
            {
                { "key1", "value1" },
                { "key2", "value2" },
                { "key3", "value3" },
                { "key4", "value4" }
            };

            // assert
            _hashTable.AsEnumerable().ShouldBeEqualTo(expected);
        }
```

2017-06-06 14:04 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +        public void Setter_ShouldRemoveElementAndDontRemoveAnotherKey_WhenSetNullValueForExistingKey()
assert перевіряє лише на існування другого ключа, про першого а ні слова

2017-06-06 14:04 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +        public void Setter_ShouldRemoveElementAndUpdateCount_WhenSetNullValueForExistingKey()
цей тест задумувався як перевірка що Count змінювється при видаленні, а не на те що воно реально щось видаляє. принцип divide and concur.

2017-06-06 14:04 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +        public void TryGet_ShoudSetOutParameterWithCorrectValue_WhenKeyExists()
лишаєш так само?

2017-06-06 14:37 UTC, smallnonsense commented on DataStructures/Source/HashTable/Entry.cs
> +            return obj != null && Key.Equals(obj.Key) && Value.Equals(obj.Value);
Здається я вже десь писав про це, але зараз не можу знайти, тому повторю.
ReferenceEqual для null, бо нащадки можуть перевизначити оператор.

2017-06-06 21:07 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +        public void Setter_ShouldRemoveElementAndDontRemoveAnotherKey_WhenSetNullValueForExistingKey()
согласен. добавил проверку на то есть ли первый элемент в таблице.

2017-06-06 21:08 UTC, MikeK93 commented on DataStructures/Source/HashTable/Entry.cs
> +            return obj != null && Key.Equals(obj.Key) && Value.Equals(obj.Value);
исправил

2017-06-08 09:33 UTC, smallnonsense requested changes

2017-06-08 09:33 UTC, smallnonsense commented on DataStructures/Program.cs
> +            Console.WriteLine($"\n{toDoList.ElementAt(0)} is done!");
краще переносів рядка не використовувати без крайньої необхідності. Натомість користуватись порожнім Console.WriteLine

2017-06-08 09:33 UTC, smallnonsense commented on DataStructures/Program.cs
> +            try
погана практика користуватись try/catch скрізь підряд. ця конструкція лише для реально виключних ситуацій, коли іншого способу перевірити немає, або реально неочікувані помилки.

2017-06-08 09:33 UTC, smallnonsense commented on DataStructures/Source/HashTable/Entry.cs
>                     (!EqualityComparer<TKey>.Default.Equals(Key, default(TKey)) && Key.Equals(obj.Key)) &&
1) що буде якщо Key чи Value буде null?
2) якщо у двох об"єктів або Key, або Value буде null, то вони що вже не рівні чи що?

2017-06-08 09:33 UTC, smallnonsense commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            RemoveNode(GetSequence().FirstOrDefault(node => node.Next.Item.Equals(item)));
чи є тест нанаступний випадок? Ти впевнений що він пройде добре?
var a = new LinkedList<string>{ null, "value" };// {null} // {"value",null} // {"value"}
Assert.DoesNotThrow(() => a.Remove("value"));

2017-06-08 09:33 UTC, smallnonsense commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            if (_head == _tale)
ну що це знову?

2017-06-08 09:33 UTC, smallnonsense commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            else if (previous == _tale)
що я писав з приводу _tale?

2017-06-08 09:33 UTC, smallnonsense commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            var nodeIndex = index >= 0 ? index : Length + index;
чи є тест який покриває випадок коли index < 0?

2017-06-08 11:22 UTC, MikeK93 commented on DataStructures/Program.cs
> +            try
почему здесь не желательно использовать try/catch?
я ожидаю что кинет ошибку по причине пустого стека.

2017-06-08 11:53 UTC, MikeK93 commented on DataStructures/Program.cs
> +            Console.WriteLine($"\n{toDoList.ElementAt(0)} is done!");
можно узнать почему `\n` или `Environment.NewLine` не стоит использовать?

2017-06-08 12:03 UTC, smallnonsense commented on DataStructures/Program.cs
> +            Console.WriteLine($"\n{toDoList.ElementAt(0)} is done!");
Environment.NewLine було б правильніше. Але який сенс якщо WriteLine робить те саме. З ними структура лінійніша буде і читатись простіше. а всякі спецсимволи не несуть навантаження, але відволікають

2017-06-08 12:06 UTC, smallnonsense commented on DataStructures/Program.cs
> +            try
Треба Ріхрета читати :) ну або бодай погуглити https://www.google.com.ua/search?q=.net+throwing+exception+performance+impact&oq=.net+throwing+exception+performance+impact&aqs=chrome..69i57.15166j0j7&sourceid=chrome&ie=UTF-8#newwindow=1&q=.net+exceptions+and+performance

2017-06-08 12:11 UTC, MikeK93 commented on DataStructures/Source/HashTable/Entry.cs
>                     (!EqualityComparer<TKey>.Default.Equals(Key, default(TKey)) && Key.Equals(obj.Key)) &&
есть бага что в HashTable можно сохранить `Entry<string, string>(null, null)`. сейчас фикшу

2017-06-08 12:19 UTC, MikeK93 commented on DataStructures/Source/HashTable/Entry.cs
>                     (!EqualityComparer<TKey>.Default.Equals(Key, default(TKey)) && Key.Equals(obj.Key)) &&
1, 2 - исправил

2017-06-08 12:50 UTC, MikeK93 commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            RemoveNode(GetSequence().FirstOrDefault(node => node.Next.Item.Equals(item)));
тест написал, прошел
хотя мне кажеться что при добавлении null нужно падать

2017-06-08 13:33 UTC, MikeK93 commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            if (_head == _tale)
пропустил такой кейс где есть только один элемент в списке и поскольку список циклический получилась бага что оно не подпадало ни под какие критерии. т.е. 
head: Node1
а поскольку циклический список, то Node1.Next = Node1;
а при удалении previous.Next = previous.Next.Next; ничего не давал

2017-06-08 13:35 UTC, MikeK93 commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            var nodeIndex = index >= 0 ? index : Length + index;
поскольку это приватный метод и из вне нет возможности прокинуть минусовый индекс то теста нету.
этот код посути тестируеться когда идет удаление первого элемента, у которого индекс 0, а предыдущим будет -1.

2017-06-08 13:46 UTC, MikeK93 commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            else if (previous == _tale)
что последний елемент можно найти и без использования _tale

2017-06-08 15:21 UTC, smallnonsense commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            var nodeIndex = index >= 0 ? index : Length + index;
це окремий випадок. дивись AddAt та RemoveAt

2017-06-08 15:43 UTC, smallnonsense commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            else if (previous == _tale)
так. тоді чому знову на нього скрізь порівнюється? тут повністю достатньо обійтись з _head.
до того ж всі порівняннь повинні базуватись якось на previous, тобто умови типу (_head == _tale) викликають бажання викинути їх з цього методу, бо не залежать від вхідних даних.

2017-06-08 15:47 UTC, smallnonsense commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            if (_head == _tale)
треба просто трохи подумати над залежністю. 
от що можуть значити наступні умови?
1) _head == _head.Next
2) _previous == _previous.Next
3) _previous.Next == _head

2017-06-08 15:49 UTC, smallnonsense commented on DataStructures/Source/HashTable/Entry.cs
>                     (!EqualityComparer<TKey>.Default.Equals(Key, default(TKey)) && Key.Equals(obj.Key)) &&
ну насправді це тобі вирішувати що є багою, а що ні. в Dictionary<>, наприклад null, null можливий, здається. А вказував я на те, що для цих випадків будуть в тебе падати NullReferenceException

2017-06-08 15:51 UTC, smallnonsense commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            RemoveNode(GetSequence().FirstOrDefault(node => node.Next.Item.Equals(item)));
деякі повинні були впасти з NullReferenceException, але я ще гляну тести.

2017-06-08 16:03 UTC, smallnonsense requested changes

2017-06-08 16:03 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            Assert.Throws<ArgumentNullException>(() => _hashTable.Add(null, Value));
ти впевнений що null неправильне значення?

2017-06-08 16:03 UTC, smallnonsense commented on DataStructures.Tests/LinkedListTests.cs
> +            Assert.Throws<ArgumentNullException>(() => list.Add(null));
аналогічно. чому не валідне?

2017-06-08 16:03 UTC, smallnonsense commented on DataStructures/Source/HashTable/HashTable.cs
> +            var entry = key != null ? GetBucket(key, _buckets).FirstOrDefault(x => x.Key.Equals(key)) : null;
цю умову простіше було б сховати в GetBasket

2017-06-08 16:03 UTC, smallnonsense commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            if (ReferenceEquals(previous, _head) && ReferenceEquals(previous, _tale))
блін, та справа ж не в Equals чи ReferenceEquals. :)
а в тому що _tale це просто оптимізація просто і не треба іі мішати до основної логіки. Воно взагалі не повинно ні на що впливати окрім швидкодії

2017-06-12 12:24 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            Assert.Throws<ArgumentNullException>(() => _hashTable.Add(null, Value));
Да. В .net dictionary тоже нельзя добавить null в качестве ключа

2017-06-12 12:27 UTC, MikeK93 commented on DataStructures.Tests/LinkedListTests.cs
> +            Assert.Throws<ArgumentNullException>(() => list.Add(null));
мне кажется что это не имеет смысла добавлять null в linedlist, да и вообще в список какой-то. от этого нет никакой пользы

2017-06-13 10:50 UTC, MikeK93 commented on DataStructures/Source/HashTable/HashTable.cs
> +            var entry = key != null ? GetBucket(key, _buckets).FirstOrDefault(x => x.Key.Equals(key)) : null;
в некоторых случаях нужно кидать ексепшн, а внекоторых эта проверка учавствует в результате, как вот тут вот.

2017-06-13 11:35 UTC, smallnonsense commented on DataStructures/Source/HashTable/HashTable.cs
> +            var entry = key != null ? GetBucket(key, _buckets).FirstOrDefault(x => x.Key.Equals(key)) : null;
1) конструкція GetBucket(key, _buckets).<link method>(x => x.Key.Equals(key)) дуже часто використовується, це признак дублювання коду. винеси її в окремий метод.
2) А випадок key == null є одним з двох окремих випадків коли не знайдено нічого. тут або всі частини коду повинні кидати помилки якщо ключ null, або ніяка. зараз бачу обидві поведінки. мені особисто здається простіше зробити щоб null був нормальним значенням для ключа і оновити логіку відповідно. але справа за тобою.
3) пам'ятаєш що я казав за використання оператора ==? що буде якщо ключ структура? а чи може структура бути null?
ось підказка
![image](https://user-images.githubusercontent.com/8962150/27080641-79ce5822-5045-11e7-96bd-ef347d0826fa.png)

2017-06-13 11:36 UTC, smallnonsense commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            if (ReferenceEquals(previous, _head) && ReferenceEquals(previous, _tale))
а тут щось міняти будеш?

2017-06-13 11:40 UTC, smallnonsense commented on DataStructures.Tests/LinkedListTests.cs
> +            Assert.Throws<ArgumentNullException>(() => list.Add(null));
чому? чим це значення гірше інших? до речі, не звертав раніше уваги, але знаєш чому стандартні реалізації фреймворка не кидають таких помилок? тому що для дженерик типів не існує поняття null? бо null це default(object).

2017-06-13 11:58 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            Assert.Throws<ArgumentNullException>(() => _hashTable.Add(null, Value));
це щось нереальну тупо. це ж гарантований boxing на порожньому місці для стуктурних типів.

2017-06-13 12:14 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            Assert.Throws<ArgumentNullException>(() => _hashTable.Add(null, Value));
![image](https://user-images.githubusercontent.com/9809523/27081840-f4a0e970-504a-11e7-9264-9438918cf312.png)

2017-06-13 12:22 UTC, MikeK93 commented on DataStructures/Source/HashTable/HashTable.cs
> +            var entry = key != null ? GetBucket(key, _buckets).FirstOrDefault(x => x.Key.Equals(key)) : null;
1. о
2. делал по принципу работы dictionary c .net

2017-06-13 12:25 UTC, MikeK93 commented on DataStructures.Tests/LinkedListTests.cs
> +            Assert.Throws<ArgumentNullException>(() => list.Add(null));
поправлю что бы можно было добавить в linkedlist, a на счет `default(struct)`:
![image](https://user-images.githubusercontent.com/9809523/27082192-75d41552-504c-11e7-8687-87604810ac93.png)

2017-06-13 12:30 UTC, MikeK93 commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            if (ReferenceEquals(previous, _head) && ReferenceEquals(previous, _tale))
нет

2017-06-13 13:56 UTC, smallnonsense commented on DataStructures.Tests/LinkedListTests.cs
> +            Assert.Throws<ArgumentNullException>(() => list.Add(null));
:) це псевдо-код. просто немає в структур такого типу що можна показати як у випадку з object

2017-06-13 13:58 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            Assert.Throws<ArgumentNullException>(() => _hashTable.Add(null, Value));
та я дивився реалізацію. вона крива :). можна заводити багу для майкрософта, якщо така ще не заведена

2017-06-15 10:32 UTC, MikeK93 commented on DataStructures/Program.cs
> +            Console.WriteLine($"\n{toDoList.ElementAt(0)} is done!");
Мне нравиться `/n` тем что она не занимает много места, но и минус есть тоже, это то что тяжело читать такое. 
Буду юзать лучше Console.WriteLine();

2017-06-15 10:34 UTC, MikeK93 commented on DataStructures/Program.cs
> +            try
Ну это я знаю что try/catch нужно избегать где только можно, и использовать окуратно и по надобносте. Но по мне это как раз то место где я ожидаю что что-то будет не то. И использование try/catch в этом месте мне кажетсья логичным.

2017-06-15 10:34 UTC, MikeK93 commented on DataStructures/Source/HashTable/Entry.cs
>                     (!EqualityComparer<TKey>.Default.Equals(Key, default(TKey)) && Key.Equals(obj.Key)) &&
ок

2017-06-15 10:35 UTC, MikeK93 commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            RemoveNode(GetSequence().FirstOrDefault(node => node.Next.Item.Equals(item)));
ок

2017-06-15 10:45 UTC, MikeK93 commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            if (_head == _tale)
1. один элемент в списке
2. кажись тоже что и 1
3. последний элемент
как по мне этот подход усложняет читабельность.

2017-06-15 10:48 UTC, MikeK93 commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            else if (previous == _tale)
при ипользовании _tale, _previous, _head как по мне читабельность кода стает только лучше так как смотря на код становиться сразу понятно что оно означает.

2017-06-15 10:52 UTC, MikeK93 commented on DataStructures.Tests/LinkedListTests.cs
> +            Assert.Throws<ArgumentNullException>(() => list.Add(null));
ok

2017-06-15 10:53 UTC, MikeK93 commented on DataStructures.Tests/HashTableTests.cs
> +            Assert.Throws<ArgumentNullException>(() => _hashTable.Add(null, Value));
ну тут как сказать, может есть на это причины :)

2017-06-15 11:06 UTC, MikeK93 commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            var nodeIndex = index >= 0 ? index : Length + index;
я пока оставлю как есть если можно. для себя вынесу отмечу переписать.

2017-06-15 13:02 UTC, smallnonsense commented on DataStructures.Tests/HashTableTests.cs
> +            Assert.Throws<ArgumentNullException>(() => _hashTable.Add(null, Value));
![image](https://user-images.githubusercontent.com/8962150/27182500-ff3c8aac-51e3-11e7-82c1-fb56c1250eb8.png)
ну який в цьому сенс?

2017-06-15 13:06 UTC, smallnonsense commented on DataStructures/Source/LinkedList/LinkedList.cs
> +            if (_head == _tale)
це лише повинно показати що _tale нічого не вирішує. тобто взагалі це зайва штука покликана лише оптимізувати один єдий випадок - добавляння в кінець списку. 
коротше дискусію немає сенсу продовжувати.

2017-06-15 13:09 UTC, smallnonsense commented on DataStructures/Program.cs
> +            try
я ок. можеш попитати думки ще когось.

2017-06-15 13:10 UTC, smallnonsense approved these changes

2017-06-15 13:26 UTC, merged